### PR TITLE
upgrade truffleruby to 1.0.0-rc13

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
cc: @eregon

**Comment by mojavelinux** [comment]
I can confirm two of the fixes from the RC12 release now produce the correct result.

**Comment by mojavelinux** [comment]
What I still don't understand is why `bundle install` is so slow. It takes 416.05s.

The tests take 262.57s, which is tolerable, but still no where near MRI or JRuby. And this is pretty plain Ruby code.

**Comment by eregon** [comment]
> I can confirm two of the fixes from the RC12 release now produce the correct result.

Good news :)

> What I still don't understand is why `bundle install` is so slow. It takes 416.05s.
> 
> The tests take 262.57s, which is tolerable, but still no where near MRI or JRuby. And this is pretty plain Ruby code.

On https://travis-ci.org/asciidoctor/asciidoctor/jobs/488821301, `bundle` ran 3 times, so it's 416s for all 3 runs, because the first 2 segfaulted unfortunately. I said this too many times today (sorry about that), but please report this to https://github.com/oracle/truffleruby/issues so we can track it more easily and other people on the team can also work on it.

**Comment by Mogztter** [comment]
Maybe related: https://github.com/oracle/truffleruby/issues/1490 
@eregon I've added a comment with a link to the SegFault

**Comment by mojavelinux** [comment]
> On [travis-ci.org/asciidoctor/asciidoctor/jobs/488821301](https://travis-ci.org/asciidoctor/asciidoctor/jobs/488821301), `bundle` ran 3 times, so it's 416s for all 3 runs,

Thanks for pointing that out. That definitely explains in part why it's taking so long.

> I said this too many times today (sorry about that), but please report this to [oracle/truffleruby/issues](https://github.com/oracle/truffleruby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) so we can track it more easily and other people on the team can also work on it.

:+1:

**Comment by mojavelinux** [comment]
Upstream issue: https://github.com/oracle/truffleruby/issues/1398

**Comment by Mogztter** [comment]
@mojavelinux we should try rc13. Truffle Ruby claims that the SegFault is fixed.

**Comment by mojavelinux** [comment]
We definitely should try rc13. However, it looks like the performance problem with Bundler is not going to be solved anytime soon, so I'm reluctant to add it to the build matrix. Otherwise, it will really slow down development. It's something we'll have to test locally.

**Comment by mojavelinux** [comment]
I tried with rc13 and it fails with numerous segfaults. I'm going to integrate these changes, but leave truffleruby disabled because it's just not ready to be on our critical release path.

**Comment by Mogztter** [comment]
> I tried with rc13 and it fails with numerous segfaults.

That's sad.
Looking at Travis, it seems that `bundle install` does not produce segfaults anymore but it's 10 times slower than JRuby:

- TruffleRuby: 279.05s
- JRuby: 27.68s

> I'm going to integrate these changes, but leave truffleruby disabled because it's just not ready to be on our critical release path.

Fair enough :+1:

**Comment by Mogztter** [comment]
I can't reproduce the segfaults on my machine but I have a few errors anyway

**Comment by mojavelinux** [comment]
If you'd like to try to fix the errors, please feel free to do so. Since it segfaults for me (and on Travis), I have no way of knowing what to change.

**Comment by Mogztter** [comment]
Sure :ok_hand: 
I also get a few "pedantic warnings":

```
[ruby] WARNING: negative line number /home/guillaume/workspace/opensource/asciidoctor/asciidoctor/test/fixtures/custom-backends/haml/html5-tweaks/block_paragraph.html.haml:-14 not supported in #class/module_eval - will be reported as starting at 1
[ruby] WARNING: negative line number /home/guillaume/workspace/opensource/asciidoctor/asciidoctor/test/fixtures/custom-backends/haml/html5-tweaks/embedded.html.haml:-14 not supported in #class/module_eval - will be reported as starting at 1
[ruby] WARNING: negative line number /home/guillaume/workspace/opensource/asciidoctor/asciidoctor/test/fixtures/custom-backends/haml/html5-tweaks/block_paragraph.html.haml:-14 not supported in #class/module_eval - will be reported as starting at 1
[ruby] WARNING: negative line number /home/guillaume/workspace/opensource/asciidoctor/asciidoctor/test/fixtures/custom-backends/slim/html5/block_paragraph.html.slim:-7 not supported in #class/module_eval - will be reported as starting at 1
[ruby] WARNING: negative line number /home/guillaume/workspace/opensource/asciidoctor/asciidoctor/test/fixtures/custom-backends/slim/html5/block_sidebar.html.slim:-7 not supported in #class/module_eval - will be reported as starting at 1
[ruby] WARNING: negative line number /home/guillaume/workspace/opensource/asciidoctor/asciidoctor/test/fixtures/custom-backends/haml/html5/block_paragraph.html.haml:-14 not supported in #class/module_eval - will be reported as starting at 1
[ruby] WARNING: negative line number /home/guillaume/workspace/opensource/asciidoctor/asciidoctor/test/fixtures/custom-backends/haml/html5/block_sidebar.html.haml:-14 not supported in #class/module_eval - will be reported as starting at 1
[ruby] WARNING: negative line number /home/guillaume/workspace/opensource/asciidoctor/asciidoctor/test/fixtures/custom-backends/haml/html5/block_paragraph.html.haml:-14 not supported in #class/module_eval - will be reported as starting at 1
[ruby] WARNING: negative line number /home/guillaume/workspace/opensource/asciidoctor/asciidoctor/test/fixtures/custom-backends/erb/html5/open.html.erb:-11 not supported in #class/module_eval - will be reported as starting at 1
[ruby] WARNING: negative line number /home/guillaume/workspace/opensource/asciidoctor/asciidoctor/test/fixtures/custom-backends/erb/html5/block_paragraph.html.erb:-11 not supported in #class/module_eval - will be reported as starting at 1
```

```
/home/guillaume/.rvm/gems/truffleruby-1.0.0-rc13@asciidoctor/gems/tilt-2.0.7/lib/tilt/haml.rb:50:in `block in precompiled_postamble': Haml::Engine#precompiled_method_return_value at /home/guillaume/.rvm/rubies/truffleruby-1.0.0-rc13/lib/mri/forwardable.rb:157 forwarding to private method Haml::TempleEngine#precompiled_method_return_value
```

Does that ring a bell ?

**Comment by Mogztter** [comment]
My bad, I can reproduce this issue, `rvm` was actually installing rc11 :man_shrugging: 
Do you want me to open an issue at https://github.com/oracle/truffleruby ?

**Comment by mojavelinux** [comment]
Sure :+1:

**Pull request merged**
