### PR TITLE
Manpage url fix

### PR DESCRIPTION
**Pull request by ds26gte**
rebased to Dec 29 morn asciidoctor#master

### CODE REVIEW

**Comment by mojavelinux** [comment]
Let me know if this works for your cases and, if so, I'll proceed with merging.

**Comment by ds26gte** [comment]
Yes. Works like a charm on all I threw at it! Merge away.

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
Merged as b1f08441a8c82c16ec8d5439c808c6e3ff67a583

**Pull request closed without merging**
