### PR TITLE
Fixed Travis Status button in README file

### PR DESCRIPTION
**Pull request by jasnow**
Fixed Travis Status button in README file.

Example: https://github.com/jasnow/asciidoctor

### CODE REVIEW

**Comment by jasnow** [comment]
New pull request

**Comment by mojavelinux** [comment]
What's the problem with using shields.io?

**Comment by jasnow** [comment]
Not familiar with shields.io but went back to it.

**Comment by mojavelinux** [comment]
That's good, but the double quotes aren't necessary. So I'm not sure a change is needed.

If we think that shields.io is too slow, then I'm willing to consider using Travis CI directly. Travis CI does offer an SVG and that's really the only requirement.

**Comment by jasnow** [comment]
Appears to not be needed since I see that travis is green now.

**Comment by mojavelinux** [comment]
:+1:

**Pull request closed without merging**
