### PR TITLE
 Update the pandoc command in the options from the deprecated "asciidoctor" to "asciidoc."

### PR DESCRIPTION
**Pull request by guglielmobartelloni**
This pull request addresses the deprecation of the "asciidoctor" command in the options by updating it to the recommended "asciidoc" command for better compatibility and adherence to current best practices.

### CODE REVIEW

**Comment by mojavelinux** [comment]
This looks good. Is there a reason you closed it?

**Comment by guglielmobartelloni** [comment]
Hi, I wanted to modify the docker line also but I forgot to 😅

**Comment by mojavelinux** [comment]
Okay. You can update a PR after you submit it. Do you want me to reopen, or do you want to make a new PR?

**Comment by guglielmobartelloni** [comment]
Oh okay then I will integrate the new change tomorrow when I'm at home. Thank you

**Comment by guglielmobartelloni** [comment]
Okay, I've successfully implemented the change. Thank you once again for your assistance.

**Comment by mojavelinux** [comment]
Thanks!

**Pull request merged**
