### PR TITLE
unnecessary ruby version rechecking

### PR DESCRIPTION
**Pull request by nplusp**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Actually, the current syntax is intentional. Opal's preprocessor looks for that exact string (`RUBY_ENGINE == 'opal'`) to decide whether to include the source code in a conditional branch. In this case, Opal skips the else branch. That's what the comment above this line is trying to communicate.

**Comment by mojavelinux** [comment]
I'd be open to a clarification to the comment line to explain this.

**Comment by nplusp** [comment]
@mojavelinux thanks for the explanation.

**Comment by Mogztter** [comment]
(For my curiosity) we can use `if RUBY_ENGINE_OPAL` in [asciidoctor.rb#L1609](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L1609) because there's no else block to skip ?

**Comment by mojavelinux** [comment]
@Mogztter It's more that it is harmless to ignore it at runtime. The reason for `RUBY_ENGINE == 'opal'` filtering is to hide something from Opal so it doesn't choke on it. So it's like extra hidden.

**Pull request closed without merging**
