### PR TITLE
Upgrade to Slim 3

### PR DESCRIPTION
**Pull request by voxik**
Why test against old Slim if there is newer version ...

### CODE REVIEW

**Comment by voxik** [comment]
Hmmm, Ruby 1.8.7 ....

**Comment by mojavelinux** [comment]
I can switch to a newer Slim in the gemspec and override it in the Gemfile for the Ruby 1.8.7 tests. (Yes, I realize 1.8.7 needs to be dropped, but I want to do that at the transition to 1.6.0, which I'm trying hard to get to).

**Comment by voxik** [comment]
I was not lobbying for removing Ruby 1.8.7 ... I just not expected the failure :)

**Comment by mojavelinux** [comment]
Oh, don't worry, we've already decided to drop Ruby 1.8.7...it's just a formality at this point.

I still want to test against a recent Slim. That may mean loosing the dependency, upgrading it in Gemfile, or something else. I'll play around with it.

**Comment by mojavelinux** [comment]
I found a way to do it. Thanks!

**Pull request merged**
