### PR TITLE
Update the link name in readme

### PR DESCRIPTION
**Pull request by awxiaoxian2020**
supplement for #4278. I found that in [README-fr.adoc](https://github.com/asciidoctor/asciidoctor/blob/main/README-fr.adoc), It does not display language names in the local language like other readme documents, but only in French. Is this a French convention or document style?

### CODE REVIEW

**Comment by awxiaoxian2020** [comment]
@flashcode Could you give me a reply? Thank you.

**Comment by mojavelinux** [comment]
It's probably just an inconsistency that crept in. I like the style that the language is its own language. That way, it is recognizable to someone looking for it.

**Comment by awxiaoxian2020** [comment]
> It's probably just an inconsistency that crept in. I like the style that the language is its own language. That way, it is recognizable to someone looking for it.
I fully share your opinion. But I think it's better to be confirmed by contributors in French. I would like to keep it open until there are any reply.

**Comment by flashcode** [comment]
Hi,

I agree with @mojavelinux, the name of each language should be translated in this language.

**Comment by mojavelinux** [comment]
Thanks again!

**Comment by awxiaoxian2020** [comment]
> Hi,
> 
> I agree with @mojavelinux, the name of each language should be translated in this language.

OK, thank you.

**Comment by awxiaoxian2020** [comment]
@mojavelinux  sorry, I made it draft as I have not changed the French doc already, I think I will have a new PR.

**Comment by mojavelinux** [comment]
I'm merging them separately because each change should be focused on a specific task. We have now updated the Simplified Chinese references, which was the first task. Changing French is a separate task. Thanks again for helping out!

**Comment by awxiaoxian2020** [comment]
> I'm merging them separately because each change should be focused on a specific task. We have now updated the Simplified Chinese references, which was the first task. Changing French is a separate task. Thanks again for helping out!

Got it, thanks!

**Pull request merged**
