### PR TITLE
Add new slide template converters

### PR DESCRIPTION
**Pull request by rahmanusta**
Those changes first proposal for template slide converters. Can we discuss the changes?

### CODE REVIEW

**Comment by mojavelinux** [comment]
Thanks for the PR @rahmanusta! However, before we continue, I think this should be in the asciidoctor.js repository instead of the Asciidoctor core repository as it's specifically for the asciidoctor.js environment. Would you agree?

(If you're concerned we won't be able to make the change from asciidoctor.js alone, you can trust me that I'll find a way to integrate it from there).

**Comment by rahmanusta** [comment]
Thank you @mojavelinux ! Yes, those converters can only work with JavaScript platforms (browser,node,nashorn ..). I see that Asciidoctor.js uses same core repository to generate JavaScript dist (https://github.com/asciidoctor/asciidoctor.js/blob/master/Gemfile#L9).

We can just put JS template converters to /dist directory but, we need to declare (https://github.com/asciidoctor/asciidoctor/pull/1450/files#diff-660cd2bae2d18e2bb4b054f51c7b1c22R215) that converters to core (asciidoctor-core.js and asciidoctor-all.js).How can we integrate those changes without touching to asciidoctor-core? If there is a way, that wil be best.

**Comment by Mogztter** [comment]
@rahmanusta 
> We can just put JS template converters to /dist directory

You can generate the JavaScript from Ruby code in Asciidoctor.js, see https://github.com/asciidoctor/asciidoctor.js/pull/119

> We need to declare that converters to core

The factory is a tricky part, I don't know how we can "overload" the `create` method in Asciidoctor.js

**Comment by rahmanusta** [comment]
Thank you @Mogztter for integration. 

  The factory is a tricky part, I don't know how we can "overload" the create method in Asciidoctor.js

I'dont know the way how to override a method in class with Opal but, If we load the Factory class again, it will override whole Factory class together with methods. @mojavelinux said me before it acts as CSS.

**Comment by Mogztter** [comment]
So I guess we can duplicate the class and load the generated JavaScript file after asciidoctor-core.js to override the factory. This is the quick and dirty solution but we can start with that and then find a better solution.

**Comment by mojavelinux** [comment]
>  I guess we can duplicate the class and load the generated JavaScript file after asciidoctor-core.js to override the factory.

Actually, the solution would just be to monkeypatch it, which is to add a Ruby file that redefines just that method. You can put any code you want into that method definition and it will be used in place of the original.

The goal should then be to change core so that we don't need to do that. Once the monkeypatch is in place, the requirement should be clear.

**Comment by mojavelinux** [comment]
Can we agree that this has been reopened in asciidoctor.js as https://github.com/asciidoctor/asciidoctor.js/pull/119?

**Comment by rahmanusta** [comment]
Yes, I agreed with @Mogztter 's PR (https://github.com/asciidoctor/asciidoctor.js/pull/119)

**Comment by mojavelinux** [comment]
Let's close this one then and continue the discussion there.

**Pull request closed without merging**
