### PR TITLE
Font Awesome5

### PR DESCRIPTION
**Pull request by asdfg0280**
try again migrate fontawesome5

### CODE REVIEW

**Comment by asdfg0280** [comment]
close #2535

**Comment by mojavelinux** [comment]
Can you please remove the vendor folder? That's the first thing that needs to happen to even consider this patch. Thanks!

**Comment by mojavelinux** [comment]
Also, can you please consolidate this to a single PR? I don't see any reason why a new PR is needed.

**Comment by asdfg0280** [comment]
sry, I mistake

**Comment by mojavelinux** [comment]
Thanks!

**Pull request closed without merging**
