### PR TITLE
Fix crash caused by empty data after line continuation symbol

### PR DESCRIPTION
**Pull request by zelivans**
Fixes https://github.com/asciidoctor/asciidoctor/issues/2880

This is a simple fix that checks that `next_line` is not nil before attempting to call `lstrip` on it. It can be tested by checking that the following example `:t: t +` does not throw an Exception.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Could you add a test? It doesn't have to be perfect as I'll likely run it myself and make adjustments if necessary. It's just important to demonstrate the fix so that I can get right to testing it.

**Comment by zelivans** [comment]
I wrote a simple test for this. I only tested with `LINE_CONTINUATION` but it follows the same logic as `LINE_CONTINUATION_LEGACY` in the code.

@mojavelinux by the way, in my fix I didn't log any warning when there is no following line after the line continuation symbol, because the bug only happens when it is the last line if I understand correctly. I don't think it really matters because no one is expected to do that anyway, but let me know if you want to also log an error.

**Comment by mojavelinux** [comment]
To avoid an unnecessary call to `lstrip`, I think we can use this logic.

```ruby
while reader.advance && !(next_line = reader.peek_line || '').empty?
  next_line = next_line.lstrip
  if (keep_open = next_line.end_with? con)
```

The redundant call to `empty?` on an empty string is acceptable since at most it can happen once per document.

**Comment by zelivans** [comment]
Thanks, this also feels more like the Ruby way to handle this. Should I commit on top? Or can you edit and own the previous commit?

**Comment by mojavelinux** [comment]
You can just commit on top if you want. When all the commits come in from one person, I tend to just squash them when I merge.

**Comment by mojavelinux** [comment]
Updated and merged as 6e95520ed12617a13fb8d67db74daebaf653e3f5.

**Comment by zelivans** [comment]
Thanks.

**Comment by mojavelinux** [comment]
Thank you!

**Pull request closed without merging**
