### PR TITLE
Trigger upstream build of AsciidoctorJ with every Travis build

### PR DESCRIPTION
**Pull request by robertpanzer**

### CODE REVIEW

**Comment by mojavelinux** [comment]
This is great. The only thing I'd like to do is get it to update the commit message of the job to something like:

"build triggered by change to asciidoctor/asciidoctor"

Otherwise, it's not clear why the build is running. I think it's just a matter of passing an additional value in the JSON payload.

See https://docs.travis-ci.com/user/triggering-builds/#Customizing-the-commit-message.

Can you add that? That would solve #2314.

**Comment by mojavelinux** [comment]
I'm also not sure if it's possible to trigger a build on the 1.6. branch as well. Can you see how? If not, we can just do master for now.

**Comment by robertpanzer** [comment]
Yes, good point! Totally forgot about 1.6.0. 
I'll check that tomorrow.

**Comment by mojavelinux** [comment]
I'm going to merge this then push a change to customize the commit message. I'd still like to explore how we can trigger the build on the 1.6 branch. It probably means we need to update the configuration set to include a target branch.

**Comment by Mogztter** [comment]
The SHA1 of the commit could be nice to quickly understand why a build is failing.

**Comment by mojavelinux** [comment]
ah, good point. would you put that in the subject of the message? or in the body?

**Comment by Mogztter** [comment]
It will be useful in the message, especially when browsing the build history on Travis:

sha1

With this view we can quickly see when the build start failing and get the corresponding sha1:
"Build triggered by change to Asciidoctor core (29bd89d)"

But we need to give it a try because I don't know if Travis will try to automatically turn it into a link on Asciidoctor.js or AsciidoctorJ (instead of Asciidoctor).

I wonder if the body text is shown on the build history ? :thinking:

**Comment by mojavelinux** [comment]
I like this idea. I guess the only way we'll know is to try, so I'll just start throwing some data at it and see what comes out.

To save space, I'll drop the word "core" as that is understood.

**Comment by mojavelinux** [comment]
> I wonder if the body text is shown on the build history ?

It's shown on the build detail page, but it's kind of faded out. We'll see if we can squeeze it into the subject.

**Comment by mojavelinux** [comment]
Okay, the URL is sort of grayed out, but you can triple click to select it.

https://travis-ci.org/asciidoctor/asciidoctor.js/builds/253796777

I'll also include the textual commit hash in the subject line.

**Comment by mojavelinux** [comment]
Let me know if you like that.

**Comment by Mogztter** [comment]
It's nice, can we use the short format for SHA1 (7 characters) ?

**Comment by mojavelinux** [comment]
Unfortunately, Travis doesn't put the short form of the SHA1 into an environment variable. So we'd have to either calculate it ourselves or use git to calculate it. But I think it's better just to have the full value. Why discard information? If you feel strongly we should use the short format, I'd need to know what strategy you'd like to use to retrieve it.

**Comment by mojavelinux** [comment]
I tested and the URL works if we just truncate the SHA1 value to 10 characters. So perhaps we should just do that. wdyt?

**Comment by mojavelinux** [comment]
We'll truncate to 8 chars. We technically only need 4 to be unique in the core project, so that should be plenty.

**Comment by Mogztter** [comment]
8 chars is perfect 👌

**Comment by Mogztter** [comment]
It looks great on mobile:

screenshot_20170721-094550

**Comment by mojavelinux** [comment]
This is nice! Thanks for sharing!

**Pull request merged**
