### PR TITLE
resolves #1633 disable toc if document has no sections

### LINKED ISSUE #1633: Hide table of contents if empty
Hide the table of contents if it would otherwise be empty. There's no point in showing an empty toc.

If, for some reason, we want to allow an empty toc, then it should require an attribute to enable it (e.g., `toc-show-if-empty`).

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
@nawroth Does this implement the desired behavior?

**Comment by nawroth** [comment]
According to the test it does!

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
Actually, I was asserting on the input instead of the output. Fixed!

**Pull request merged**
