### PR TITLE
use terminology for find_by that better aligns with NodeFilter

### PR DESCRIPTION
**Pull request by mojavelinux**
- assume that true implies "accept"
- assume that false implies "skip"
- prefer :reject rather than :skip
- prefer :terminate instead of :skip_children

### CODE REVIEW

**Comment by mojavelinux** [comment]
@Mogztter What do you think about this change? Specifically, how do you feel about the name "terminate" to "reject children"?

I managed to add the new keywords without breaking backwards compatibility. Technically, `:skip` is the wrong directive for ignoring children (according to the NodeFilter from DOM), but since `false` implies `:skip` already, we can simply add `:reject` and allow `:skip` to be used as an alias for `:reject`.

**Comment by Mogztter** [comment]
I like it :+1:

**Comment by mojavelinux** [comment]
Actually, terminate would be misleading because it gives the impression that the search stops entirely. What we're trying to express is that the recursive descent does not continue past the current node. With that in mind, let's choose from these words:

* truncate
* crop
* clip
* cut
* pare
* prune

I kind of like prune the best. It gives you the picture of cutting off branches from a trunk, which is precisely what we're doing.

**Comment by Mogztter** [comment]
> Actually, terminate would be misleading because it gives the impression that the search stops entirely. What we're trying to express is that the recursive descent does not continue past the current node. With that in mind, let's choose from these words:

It's true but you can also read it as "terminate" the current "branch" (and not terminate the whole search).

> I kind of like prune the best. It gives you the picture of cutting off branches from a trunk, which is precisely what we're doing.

It might be because I'm using git a lot but I also like prune :+1:

**Comment by mojavelinux** [comment]
Let's go with prune.

**Pull request merged**
