### PR TITLE
upgrade font awesome to 4.6.1

### PR DESCRIPTION
**Pull request by allenan**
Addresses issue: https://github.com/asciidoctor/asciidoctor/issues/1723

### CODE REVIEW

**Comment by Mogztter** [comment]
Wow that was quick! Thanks @allenan :smile: 
Font Awesome just released a bug fix version 4.6.1. Could you please upgrade ?

**Comment by allenan** [comment]
@Mogztter updated!

**Comment by Mogztter** [comment]
LGTM! :+1:

**Comment by mojavelinux** [comment]
Thanks @allenan!

**Pull request merged**
