### PR TITLE
resolves #3214 extract as variables to workaround a scope conflict in Opal

### LINKED ISSUE #3214: Regexp MatchData special variables are not properly resolved in Opal
As a result the following AsciiDoc contents will be incorrectly parsed:

#### Input

```adoc
ifeval::["{backend}" == "html5"]
Hello HTML5
endif::[]
```

#### Current output

```
start_with?: undefined method `start_with?' for nil
    at constructor.$$method_missing (/home/guillaume/workspace/opensource/nodebook/node_modules/asciidoctor-opal-runtime/src/opal.js:3907:56)
    at constructor.method_missing_stub (/home/guillaume/workspace/opensource/nodebook/node_modules/asciidoctor-opal-runtime/src/opal.js:1310:35)
    at constructor.$$resolve_expr_val (/home/guillaume/workspace/opensource/nodebook/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:14158:68)
    at /home/guillaume/workspace/opensource/nodebook/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:13648:183
    at constructor.$$preprocess_conditional_directive (/home/guillaume/workspace/opensource/nodebook/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:13652:32)
    at constructor.$$process_line (/home/guillaume/workspace/opensource/nodebook/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:13524:37)
    at constructor.$$peek_line (/home/guillaume/workspace/opensource/nodebook/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:12738:41)
    at Opal.send (/home/guillaume/workspace/opensource/nodebook/node_modules/asciidoctor-opal-runtime/src/opal.js:1671:19)
    at constructor.$$peek_line (/home/guillaume/workspace/opensource/nodebook/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:13292:29)
    at Function.$$parse_block_metadata_line (/home/guillaume/workspace/opensource/nodebook/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:11211:55)
```

#### Expected output

```html
Hello HTML5
```

#### Input

```adoc
:adjective: strong
pass:normal[*really* {adjective} \]]
```

#### Current output

```html
<p>*really* {adjective} ]</p>
```

#### Expected output

```html
<p><strong>really</strong> strong ]</p>
```

#### Input

```adoc
:value: 4
stem:normal[\\sqrt{{value}} = 2 \]]
```

#### Current output

```html
<p>\$\\sqrt{{value}} = 2 ]\$</p>
```

#### Expected output

```html
<p>\$\\sqrt{4} = 2 ]\$</p>
```

I believe the passthrough syntax with `++` or `+++` is also affected.

### PR DESCRIPTION
**Pull request by Mogztter**
resolves #3214

Workaround for this issue: https://github.com/opal/opal/issues/1961

Resolve a major issue in Asciidoctor.js 2.0.0 when using conditional expressions: https://github.com/oncletom/nodebook/pull/371

If necessary we could use this code only when running in Opal to avoid the variables assignments in other runtimes.

### CODE REVIEW

**Comment by mojavelinux** [comment]
I'm actually in the process of working on this. I decided to go a bit deeper. When I have the change complete, I'll append to this PR.

It would be a good idea to make sure there's a test in Asciidoctor.js for any line we touch.

**Comment by mojavelinux** [comment]
Btw, I don't think a change to Opal is required. It's reasonable to assign the variables a bit earlier (and in most cases it makes the code easier to understand anyway). However, we do need to make sure we have coverage so we don't accidentally break it when refactoring.

**Comment by mojavelinux** [comment]
Can you create an issue so we can schedule it for 2.0.3?

**Comment by mojavelinux** [comment]
Go ahead and give that a test and see if it works out.

**Comment by Mogztter** [comment]
> Can you create an issue so we can schedule it for 2.0.3?

Sure :+1: 

> Go ahead and give that a test and see if it works out.

Ok.

> I'm actually in the process of working on this. I decided to go a bit deeper. When I have the change complete, I'll append to this PR.

I just saw your comment.
In the meantime I've added two more fixes where I believe Opal will get lost. I will add tests in Asciidoctor.js to validate my assumption.

**Comment by Mogztter** [comment]
Ooops I force-pushed and erased https://github.com/asciidoctor/asciidoctor/commit/61be2be37a0b561b41809f7931091943ff5ff460 :sweat_smile: 

Could you please reapply your commit ? I've added tests in Asciidoctor.js: https://github.com/asciidoctor/asciidoctor.js/pull/703 but maybe I missed some cases because you did more changes than me.

**Comment by Mogztter** [comment]
Related issue: https://github.com/asciidoctor/asciidoctor/issues/3214

**Comment by mojavelinux** [comment]
I've updated.

**Comment by mojavelinux** [comment]
This PR includes a fix for #3216. I'm going to split that out.

**Comment by Mogztter** [comment]
Nice one less 🐛

**Comment by Mogztter** [comment]
The code is also much clearer 👍

**Comment by mojavelinux** [comment]
I'll rebase once I merge the fix for #3216.

**Comment by mojavelinux** [comment]
Thanks! Hopefully that does the trick.

**Comment by Mogztter** [comment]
@mojavelinux build is green on master: https://travis-ci.org/asciidoctor/asciidoctor.js/builds/512038246

**Comment by mojavelinux** [comment]
woot!

**Pull request merged**
