### PR TITLE
Adds option to include the section number in a cross-reference

### PR DESCRIPTION
**Pull request by fap-**
This is my implementation for the proposal I made in [asciidoctor-pdf-464](https://github.com/asciidoctor/asciidoctor-pdf/issues/464#issuecomment-259584614).
I broke one test but I currently don't understand how and why.
Feedback would be welcome.

### CODE REVIEW

**Comment by fap-** [comment]
Okay, so the test breaks because the references get set in a different order after my changes and Document#register doesn't overwrite :ids by default.
I'm not sure what's the best way to handle this. Registering the references in Section#set_reference with :force would fix the test but wouldn't guarantee that the first appearance of a reference id would be the one in the final document; which I assume is the desired behavior?

**Comment by mojavelinux** [comment]
I still think we can simplify this a lot. I believe the right solution is to store the node instead of the text in the references table (at the time the ID is being stored). Then, we just need a helper method like reftext on the node that does something similar to what the title method does. It puts everything together during conversion to output the reference text in the specified style. (There's still a lot of rework we need in the model to handle sections properly, but it's doable).

We want to try to keep as much of this out of the view of the user as possible. That's why I don't think we should be messing with section-label (which should be static) and reftext (which is really for modifying the text part of the reference, not the whole reference string). Where this all belongs is in the converter, with helper methods on node. The parser shouldn't really even know about any of this, IMO.

**Comment by mojavelinux** [comment]
I've added additional comments to #858 about how I think this should be implemented. I'm working on a prototype, which hopefully I'll push later this week.

**Comment by fap-** [comment]
Closing this PR then. Thank you.

**Comment by mojavelinux** [comment]
I'll still use this PR as a reference, and probably take some of the tests. I just need to integrate all these ideas together. Then I'll have you review the new proposal and we can collaborate on that to make sure we hit all your needs.

**Pull request closed without merging**
