### PR TITLE
Synchronize Japanese README with English version (PR #3301)

### PR DESCRIPTION
**Pull request by soishino**
Updated the Japanese README to make the content the same as the latest English version line by line.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Could you request someone to review the changes as I'm unable to verify myself. Thanks!

**Comment by soishino** [comment]
Thanks @mojavelinux ! I'll ask someone to review.

**Comment by soishino** [comment]
@wotsushi Could you review the translation changes of this README-jp.adoc? I see you are the most recent contributor to the current translation of README-jp  (in #2719 ). I'd appreciate it very much if you could review the new updates I made.

I synchronized the Japanese version with the latest English version line by line using the current Japanese text as much as possible.

I hope you could help this update. Thanks!

**Comment by wotsushi** [comment]
@soishino OK, I'll review the changes(perhaps, next Saturday or Sunday). Thanks!

**Comment by wotsushi** [comment]
@soishino There is no problem! I think your translation is so good. Thank you for your contribution. 😄 
(I'm sorry for the late reply.)

**Comment by wotsushi** [comment]
@mojavelinux Could you approve this PR?  I think there is no problem.  🙆‍♂

**Comment by mojavelinux** [comment]
Indeed. Great teamwork! Thanks to both of you!

**Comment by soishino** [comment]
@wotsushi, great! Thank you so much for your help! :smiley:
@mojavelinux, I am very happy my PR is merged to this project. Thank you very much!

**Comment by mojavelinux** [comment]
@soishino Congratulations and welcome to the group!

**Pull request merged**
