### PR TITLE
Adds a warning if verbose is set and xref is not found

### LINKED ISSUE #2268: Warning if reference cannot be found
I frequently find that a reference is not working anymore. Would be great if Asciidoctor could (either always or optional) issue a warning for that.

We use a small Gradle extension to fail our documentation builds if a warning is issued. 

Would be great if we could avoid having missing cross-references also.

Example:
````
[[testing]]
== Section 1

== Section 2

See <<testing1>>.
````

### PR DESCRIPTION
**Pull request by fap-**
The warning has the following form:
asciidoctor: WARNING: could not resolve xref:

closes #2268

### CODE REVIEW

**Comment by mojavelinux** [comment]
I think the warning should go in the else of the present condition. Otherwise, a valid reference by title (e.g., `<<Section Title>>`) would generate a warning.

Otherwise, I agree this is the right approach.

**Comment by mojavelinux** [comment]
I applied some revisions.

**Comment by mojavelinux** [comment]
I'm going to merge this. Let me know if you have any further comments or concerns afterwards.

**Comment by mojavelinux** [comment]
I'm going to merge this. Let me know if you have any further comments or concerns afterwards.

**Comment by mojavelinux** [comment]
When you send pull requests, can you start the subject line with `resolves #nnn`. That allows GitHub to automatically link to and close the issue when merged.

**Comment by fap-** [comment]
Thank you.

You don't have to put the closing keyword into the subject line.
You can put it anywhere in the commit message (I've put it in the body this time).

**Comment by mojavelinux** [comment]
You're welcome.

I understand that GitHub now looks anywhere in the commit message. But if the number is not in the subject line, then it's not easily visible in the history (https://github.com/asciidoctor/asciidoctor/commits/master), and that makes it harder to put together the release notes.

**Comment by mojavelinux** [comment]
I should probably be more clear that I have a script to create release notes that looks for certain patterns. And it only looks in the subject.

**Comment by fap-** [comment]
Oh, sorry, I'll put it always in the subject from now on.

**Pull request merged**
