### PR TITLE
Add link for MIT license

### PR DESCRIPTION
**Pull request by glamouracademy**

### CODE REVIEW

**Comment by mojavelinux** [comment]
I'd rather link to the LICENSE file in the project. So if we do make a change here, it would be:

```
{uri-license}[the MIT license]
```

**Comment by glamouracademy** [comment]
totally makes sense. I'll update and squash.

**Comment by glamouracademy** [comment]
Updated! Thanks!

**Comment by mojavelinux** [comment]
Thanks!

**Pull request merged**
