### PR TITLE
Port tests to haml 6

### PR DESCRIPTION
**Pull request by terceiro**
Fixes: #4382

### CODE REVIEW

**Comment by mojavelinux** [comment]
Thanks for taking this on!

We will still need to test again Haml 5 for compatibility reasons. Would you be able to add conditionals in such a way that the tests work with either version? I'll then make sure the CI matrix is set up to run on both major versions.

**Comment by terceiro** [comment]
> Thanks for taking this on!
> 
> We will still need to test again Haml 5 for compatibility reasons. Would you be able to add conditionals in such a way that the tests work with either version? I'll then make sure the CI matrix is set up to run on both major versions.

There.

**Comment by mojavelinux** [comment]
Thanks! I'll review as soon as you think it's ready to go. Just give me the signal.

**Comment by terceiro** [comment]
this should be ready. I tested against haml 5 and 6 by hacking the Gemfile, and it works

**Comment by thesamesam** [comment]
Thanks for this, I was just trying to figure out why the tests were failing for us :)

@mojavelinux able to take a look?

**Comment by mojavelinux** [comment]
Superseded by #4431.

I don't want to introduce an intermediary class to add support for Haml 6, and I don't think it's necessary. Instead, I want to use the existing infrastructure in the template converter to deal with option variance. However, this PR did point me to what needed to be changed, so I very much appreciate the contribution.

>  I tested against haml 5 and 6 by hacking the Gemfile, and it works

We can't just rely on local testing. I added a profile to the CI workflow to run the test suite using Haml 5 in additional to Haml 6.

**Pull request closed without merging**
