### PR TITLE
Add warning about Google Fonts to documentation

### LINKED ISSUE #4540: Warn users about the use of Google Fonts
The use of Google Fonts in Asciidoctor-generated HTML (that uses the default style and doesn't go out of its way to add a consent form) violates the GDPR - see [here for example](https://www.cookieyes.com/documentation/google-fonts-and-gdpr/).

As stated [here](https://github.com/asciidoctor/asciidoctor/issues/2515#issuecomment-1915402879):

> A majority of users prefer and rely on this feature, so the default will not be changed.

I'll give you the benefit of the doubt for that, but either way it doesn't help users who don't even *know* about the use of Google Fonts. I was certainly very surprised to see that I was *accidentally* violating the GDPR. It was surprising that Asciidoctor by default uses Google Fonts.

I think you should at least warn users about this. It is mentioned [here](https://docs.asciidoctor.org/asciidoctor/latest/html-backend/default-stylesheet/#web-fonts) but that is pretty deep in the docs and not highlighted. I would suggest a note on the command line like

```
NOTE: Using Google Fonts.
```

Or failing that, a warning box on [this page](https://docs.asciidoctor.org/asciidoctor/latest/html-backend/).

Alternatively, you could inline the fonts. WOFF2 fonts are very small (a few 10s of kB). That may be a better solution actually. Would you accept a PR for that?

### PR DESCRIPTION
**Pull request by Timmmm**
Fixes #4540

### CODE REVIEW

**Comment by mojavelinux** [comment]
> To avoid this issue you can <<Apply a Custom Stylesheet>>.

This recommendation is too drastic. You only have to unset the `webfonts` attribute and the Google Fonts will not be loaded. It's a completely reasonable compromise.

**Comment by Timmmm** [comment]
Yeah that makes sense. Only thing I would change is to include the actual code for how to unset the attribute so people don't have to look it up. I'll update the PR.

**Comment by mojavelinux** [comment]
I'd rather link to the section about webfonts (https://docs.asciidoctor.org/asciidoctor/latest/html-backend/default-stylesheet/#disable-or-modify-the-web-fonts). There's no need to duplicate the information. Then it just has to be maintained in multiple places.

**Comment by mojavelinux** [comment]
Were you going to make this update, or would you like me to proceed with the text I proposed?

**Comment by Timmmm** [comment]
I was going to do it but I'd you'd like to just get it done please go ahead! I am very short on free time unfortunately :/

**Comment by mojavelinux** [comment]
Sure thing, I can take care of it. I just didn't want to step on any toes.

**Comment by mojavelinux** [comment]
This information has been added in 5cfd8adfdae60ca1168315a78999c80610c91568. See https://docs.asciidoctor.org/asciidoctor/latest/html-backend/

**Comment by Timmmm** [comment]
Thanks! :tada:

**Pull request closed without merging**
