### PR TITLE
Extract stylesheet handling into separate class

### PR DESCRIPTION
**Pull request by martijnversluis**
To extract functionality and responsibility parts of the code can be
extracted into isolated classes that return an array containing lines
of HTML. These classes could even be unit tested if necessary and
desirable.

I'm really curious what you think of this approach.

### CODE REVIEW

**Comment by martijnversluis** [comment]
The Travis build is failing in a really weird way for two JRuby versions. Could you help me debugging that?

**Comment by martijnversluis** [comment]
@mojavelinux Any thoughts on this?

**Comment by martijnversluis** [comment]
Hi @mojavelinux. Thanks for your reply. The main reason for creating this PR is the fact that you explicitly welcome refactoring PRs in the README. I tried to propose an approach to slowly improve the readability and maintainability of the code. I agree that having a quick conversion is important, but I think it might affect code quality too much.

So I would like to know whether or not you think this approach makes sense. I agree the naming collision with the existing `Stylesheet` class should be resolved.

**Comment by mojavelinux** [comment]
I'm willing to discuss code quality anywhere but the built-in HTML converter. As I stated, I view the built-in converter as compiled code. It's meant to be fast, not readable. Given I'm using Asiidoctor to process tens of thousands of documents, we cannot afford to lose any speed. (I've also become very accustomed to working with it the way it is, so for me it's readable enough given what we are trying to achieve).

At this point, I don't want to modify the current built-in HTML converter because I don't want to continue to invest in it. What I would l like to do is start making headway on a next generation HTML converter that maximizes semantics. See #242. That's where I'd be open to rethinking how we write and maintain the converter. I'll still be concerned about performance, but since it's new territory, we won't have the same expectations to uphold. And a new structure might be more efficient anyway.

**Comment by martijnversluis** [comment]
Ok, fair enough. Then this PR simply does not fit your roadmap I guess. Thanks for your replies anyway.

**Pull request closed without merging**
