### PR TITLE
Fix a typo base64 data

### PR DESCRIPTION
**Pull request by Mogztter**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Thanks for catching this! It looks like this line is 3 years old, which means we are missing a test case. Could you insert one here https://github.com/asciidoctor/asciidoctor/blob/master/test/blocks_test.rb#L1811 ?

**Comment by Mogztter** [comment]
> Thanks for catching this! It looks like this line is 3 years old, which means we are missing a test case.

An Asciidoctor.js test case caught it :wink: 

> Could you insert one here

Sure

**Comment by Mogztter** [comment]
Done!

**Comment by mojavelinux** [comment]
Thanks @Mogztter! Now we're covered in both places!

**Pull request merged**
