### PR TITLE
Run pygments with startinline = true

### PR DESCRIPTION
**Pull request by ricpelo**
Works better for PHP language.

### CODE REVIEW

**Comment by ramsey** [comment]
Does this always turn on `startinline`? If so, that may not be desirable in all cases.

**Comment by mojavelinux** [comment]
What I would prefer is to either:

* break php into two langauges, php and phpinline
* add an option to the block for inline mode, opts=inline

Then we can do the right thing.

I'm leaning more towards the second. wdyt?

**Comment by mojavelinux** [comment]
I've seen other discussions about this setting, such as in Jekyll, and most people agree it shouldn't be the default.

**Comment by ramsey** [comment]
I agree that an option to the block for inline mode is the right approach.

**Comment by ricpelo** [comment]
I agree: the best is to have an option for the block.

**Comment by mojavelinux** [comment]
@ricpelo Would you like to update the PR? Check for the language and if it is php, then check for the option. Something like:

```ruby
opts[:startinline] = true if lexer.name == 'PHP' && (option? 'startinline')
```

**Comment by mojavelinux** [comment]
Given that this behavior is unique to Pygments, and all other source highlighters just highlight PHP normally, I'm incline to just go ahead and set this. If I decide to make at an option before the release, I'll just update the code and document it here.

**Comment by mojavelinux** [comment]
As it turns out, this will break "mixed mode" PHP. Therefore, I propose that if the option "mixed" is set, then we disable this option. Otherwise, we enable it by default since most of the time, a fragment of pure PHP is being highlighted.

See the related issue in Asciidoctor PDF, where I am exploring these ideas. https://github.com/asciidoctor/asciidoctor-pdf/issues/755

**Comment by mojavelinux** [comment]
@ricpelo I'd like to get your thoughts on the related issue. I think we're close to formalizing the option.

**Comment by ramsey** [comment]
Won't this break everyone's documents who are currently using PHP and having to use the PHP open tag to make highlighting work?

**Comment by ramsey** [comment]
Since mixed mode is the default on Pygments, I would use it as the default here, since that's the expected behavior.

**Comment by ricpelo** [comment]
@mojavelinux I think you're right: `startinline` option enabled by default works great with any PHP snippet, with or without the `<?php` tag. About mixing HTML and PHP code, remember that Pygments have the `html+php` lexer specifically for that. See http://pygments.org/demo/6343473/ for example.

**Comment by mojavelinux** [comment]
@ramsey From my research, all the integrations are switching to enabling startinline by default, including code highlighting on GitHub. So I'd argue if we don't follow that, we will look broken. But what we offer that others don't is the ability to switch it back off by using `source%mixed`.

@ricpelo Yes, another option is to simply set the language to "html+php". That also works. So we don't break that option at all. And that convinces me even more that using startinline by default for "php" is the right choice. You can use "source,php" for pure PHP. You can use either "source%mixed,php" or "source,html+php" for mixed mode (or a full PHP document that's enclosed in PHP tags).

**Comment by mojavelinux** [comment]
@ramsey To answer your question even more directly, the only thing that breaks if you have a full PHP document enclosed in PHP tags without setting the `mixed` option (or html+php language) is the highlighting of the PHP start tag itself. It does not actually break the highlighting of the code.

**Comment by ramsey** [comment]
Sounds great, then. Looking forward to seeing this. Thanks!

**Pull request merged**
